server:
  port: 8080

management:
  endpoints.web.exposure.include: ['prometheus', 'health']
  metrics:
    export:
      prometheus.enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true