{
 "title": "Custom Metrics of Prometheus-Grafana-Example application",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Время получения ответа от /api/hello",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "increase(timedControllerHello_seconds_sum[1m]) / increase(timedControllerHello_seconds_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Время выполнения метода callCalcTimeByScheduler",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "increase(timedScheduler_seconds_sum[1m]) / increase(timedScheduler_seconds_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Случайное значение",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "expr": "randValue", "legendFormat": "__auto" }
   ]
  }
 ]
}